name: "Coding Standards"

on:
  push: null
  pull_request: null

jobs:
  coding_standards:
    name: "EditorConfig"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Check adherence to EditorConfig"
        uses: "greut/eclint-action@v0"
