name: Tests

on:
  pull_request: null
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  benchmarks:

    name: Benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 1s
          --health-timeout 1s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: redis, relay
          tools: composer
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Test benchmarks
        run: composer run bench -- --runs=1

  laravel:

    name: Laravel ${{ matrix.laravel }} (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        include:
          - laravel: '11'
            php: '8.2'
          - laravel: '12'
            php: '8.2'
          - laravel: '13'
            php: '8.3'

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 1s
          --health-timeout 1s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, relay
          tools: composer
          coverage: none

      - name: Create Laravel app
        run: composer create-project laravel/laravel example-app "^${{ matrix.laravel }}.0" --no-interaction --prefer-dist

      - name: Install Composer dependencies
        working-directory: example-app
        run: |
          composer config repositories.cachewerk/relay path ${{ github.workspace }}
          composer require cachewerk/relay @dev --no-interaction

      - name: Make and run test command
        working-directory: example-app
        run: |
          php artisan make:command VerifyRelay --no-interaction
          sed -i 's|//|dump(\\CacheWerk\\Relay\\Laravel\\Relay::stats(), \\Illuminate\\Support\\Facades\\Redis::info());|' app/Console/Commands/VerifyRelay.php
          REDIS_CLIENT=relay php artisan app:verify-relay
